# Generated by Django 3.1.1 on 2020-09-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndsv', '0003_auto_20200929_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='etchingplate',
            name='transmitted_by',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='etchingplate',
            name='transmitted_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
